export default {
  "login": "OmarAdamMostafa",
"id": 115920338,
"node_id": "U_kgDOBujN0g",
"avatar_url": "https://avatars.githubusercontent.com/u/115920338?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/OmarAdamMostafa",
"html_url": "https://github.com/OmarAdamMostafa",
"followers_url": "https://api.github.com/users/OmarAdamMostafa/followers",
"following_url": "https://api.github.com/users/OmarAdamMostafa/following{/other_user}",
"gists_url": "https://api.github.com/users/OmarAdamMostafa/gists{/gist_id}",
"starred_url": "https://api.github.com/users/OmarAdamMostafa/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/OmarAdamMostafa/subscriptions",
"organizations_url": "https://api.github.com/users/OmarAdamMostafa/orgs",
"repos_url": "https://api.github.com/users/OmarAdamMostafa/repos",
"events_url": "https://api.github.com/users/OmarAdamMostafa/events{/privacy}",
"received_events_url": "https://api.github.com/users/OmarAdamMostafa/received_events",
"type": "User",
"site_admin": false,
"name": "OmarAdamMostafa",
"company": null,
"blog": "",
"location": null,
"email": null,
"hireable": null,
"bio": "BUE Graduate / Front End Developer & UI/UX Designer",
"twitter_username": null,
"public_repos": 3,
"public_gists": 0,
"followers": 0,
"following": 0,
"created_at": "2022-10-16T08:11:34Z",
"updated_at": "2022-10-29T09:50:04Z"
};
